### ISSUE TITLE
Including bats-support as a submodule causes submodule update to fail on projects which use bats-file as a submodule

### ISSUE THREAD

**Issue by Shogoll** [bats-core/bats-file#58]
I am using bats-file for a project, and bats-file is included as a submodule in the repository. Attempting to execute `git submodule update --init` results in a error.

```
git submodule update --init --recursive
fatal: No url found for submodule path 'bats/bats-file/bats-support' in .gitmodules
fatal: Failed to recurse into submodule path 'bats/bats-file'
```

I have managed to work around the issue by rolling back to commit cc3fb8c, but I was wondering if this breaking change is intentional?

**Comment by martin-schulze-vireso** [comment]
This was an accident that made it through the review process. I removed this on master.
