### ISSUE TITLE
Most recent release (0.3.0) much behind 'master' / Any new release planned?

### ISSUE THREAD

**Issue by soblom** [bats-core/bats-file#62]
Hello, 

I was aware of BATS for a while and recently discovered `bats-file`. So I started to eagerly integrate it into my tests. That's when I realised that the status of  `master` and the last release `v0.3.0` (installed via Homebrew) are significantly apart in time (3 years) and features. It is easy enough to install the bleeding edge via `git submodule` into my project, so nothing technically stops me from using the latest goodness, but I still wanted to ask if there are any plans to continue putting out actual releases? 

I assume that some thought and effort goes into declaring a certain state of the project as a release, compared to just using the latest state in `master` and given that this is a testing tool, I would not mind to be conservative,  going from official release to official release, just that in this particular case the delta is so big. Unless the general view is that master is sufficiently stable and that everyone happily uses just that?

Thanks for the great work on bats-*, it is a really welcome support for scripting.

**Comment by hugocf** [comment]
I second that. Please can you add a new version tag? The current `0.3.0` is missing functions like `assert_file_not_permission` and `assert_file_not_contains`.

This would allow bumping the version in the official `bats/bats` Docker image to include these functions
https://github.com/bats-core/bats-core/blob/master/Dockerfile#L7

**Comment by martin-schulze-vireso** [comment]
I don't think there is a release plan or rythm, so I just published v0.4.0.
